### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ryan-blunden** [getsentry/raven-swift#16]
Please add Carthage support! Cocoa Pods is very opinionated where as Carthage simply provides a way to satisfy listed dependencies and output a framework.

**Comment by benzguo** [comment]
Carthage works (just added this to a project)
```
github "getsentry/raven-swift"
```

**Comment by timorzadir** [comment]
@ryan-blunden Are you having issues with Carthage and raven-swift, or is it just that the documentation does not mention Carthage compatibility?

**Comment by ryan-blunden** [comment]
Just that it wasn't mentioned in the docs.

On Sunday, 6 December 2015, Tommy Mikalsen <notifications@github.com> wrote:

> @ryan-blunden <https://github.com/ryan-blunden> Are you having issues
> with Carthage and raven-swift, or is it just that the documentation does
> not mention Carthage compatibility?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getsentry/raven-swift/issues/16#issuecomment-162239129>
> .
>


-- 
Cheers,
Ryan

http://www.linkedin.com/in/ryanblunden
http://ryanblunden.com
