### ISSUE TITLE
Global exception handler does not handle exceptions

### ISSUE THREAD

**Issue by jmhooper** [getsentry/raven-swift#17]
I'm using Sentry in a Swift iOS application. I'm trying to get it to report an unhandled exception and it will not. It works fine if I do something like capture a message, but global exceptions are a no go.

This is what my app delegate looks like:

```swift
import UIKit
import RavenSwift

@UIApplicationMain
public class HUAppDelegate: UIResponder, UIApplicationDelegate {
    
    public var window: UIWindow?

    public func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        configureSentry()
        let value = NSUserDefaults.standardUserDefaults().boolForKey("sentry test")
        NSUserDefaults.standardUserDefaults().setBool(!value, forKey: "sentry test")
        NSUserDefaults.standardUserDefaults().synchronize()
        if value == true {
            [1, 2][3]
        }
        return true
    }   

    private func configureSentry() {
        if let sentryDSN = SENTRY_DSN {
            RavenClient.clientWithDSN(sentryDSN)
            RavenClient.sharedClient?.setupExceptionHandler()
        }
    }
}


```

 I've set it up so that every other time the app is started it will cause an array out of bounds error. This seems like the sort of thing that should be reported to sentry but I get nothing.

**Comment by dcvz** [comment]
anything on this? I've also tried with an out of bounds error and no report.

**Comment by asbjornu** [comment]
@dcvz, @jmhooper As @dcramer [wrote in the raven-objc repository](https://github.com/getsentry/raven-objc/issues/56#issuecomment-174578817), work is underway on a new Swift client, so my and @timorzadir's investment in the existing client is greatly reduced. If you figure out a solution, we're more than happy to merge a pull request, but I doubt that we're going to spend any time debugging this. Sorry.

**Comment by timorzadir** [comment]
The issue exists because of lack of signal handlers in the client. I've been working on a fix, but now we are just waiting for the shiny new client.

**Comment by Klemen1337** [comment]
Any progress?

**Comment by julien-c** [comment]
Hi! 

Does this mean that this client doesn't currently report any crash? Do people mostly use the Obj-C client for now then?

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry-swift

**Comment by julien-c** [comment]
Got it @dcramer, thanks
