### ISSUE TITLE
New CocoaPod Version, Please?

### ISSUE THREAD

**Issue by JRG-Developer** [getsentry/raven-swift#28]
The current version of Raven Swift, `0.4.0`, has warnings due to using older Swift syntax.

This was fixed by commit `1824796`, but there hasn't been a new tagged and released version for this on CocoaPods.

Consequently, any pods that use this as dependency must specify `--allow-warnings` in order to `pod repo push` to a pod spec repo. This is a bit cumbersome to have to do every time.

Can you please push a new version to CocoaPods trunk? 😄

**Comment by timorzadir** [comment]
Done

**Comment by JRG-Developer** [comment]
Thanks!

👍
