### ISSUE TITLE
Add instructions for Cocoapods with -pre

### ISSUE THREAD

**Issue by bzmwillemsen** [getsentry/raven-swift#3]
Cocoapods has support for swift in beta right now. Here are the steps to install raven-swift if ya want.

Note that you have to use 0.1.0 tag because the pods spec was removed from the repo after 0.1.0

Steps
1. Install Cocoapods beta: `gem install cocoapods -pre`
2. Add raven swift to podfile: `pod 'raven-swift', :git => 'https://github.com/getsentry/raven-swift.git', :tag => '0.1.0'`
3. Install pods: `pod install`

**Comment by timorzadir** [comment]
Thanks! I just added it to the docs. Will add the podspec back for the next release.
