### ISSUE TITLE
Setting the release

### ISSUE THREAD

**Issue by nevir** [getsentry/raven-swift#32]
Does raven-swift have a facility for setting the `release` attribute of a reported event?  On the raven-objc side we had [`[client setRelease:]`](https://github.com/getsentry/raven-objc/blob/740cea5ce93bfb65fe3155691d6358a915594de1/Raven/RavenClient.m#L53-L55)

**Comment by asbjornu** [comment]
@nevir Perhaps the [sentry-swift](https://github.com/getsentry/sentry-swift/) client has support for this?

**Comment by nevir** [comment]
yup! using that client now; sorry about the noise
